# Generated by Django 2.1.2 on 2018-10-04 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_is_anonymous', models.NullBooleanField(default=None, editable=False)),
                ('user_text', models.TextField(default='', editable=False)),
                ('request', models.CharField(default='', editable=False, max_length=255)),
                ('session', models.CharField(default='', editable=False, max_length=255)),
                ('action', models.SlugField(editable=False)),
                ('data', jsonfield.fields.JSONField(blank=True, default=None, editable=False, null=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'trail',
            },
        ),
        migrations.CreateModel(
            name='TrailMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(default='', editable=False, max_length=255)),
                ('obj_pk', models.CharField(editable=False, max_length=255)),
                ('obj_text', models.TextField(default='', editable=False)),
                ('data', jsonfield.fields.JSONField(blank=True, default=None, editable=False, null=True)),
                ('ctype', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='trailmarkers+', to='contenttypes.ContentType')),
                ('trail', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='trails.Trail')),
            ],
            options={
                'ordering': ['-trail__created'],
                'verbose_name': 'marker',
            },
        ),
    ]
